= Robot Controller Application Template - Spring Boot Booster

IMPORTANT: This application requires Java 8 JDK or greater and Maven 3.3.x or greater.



== Running the App Locally

To run this application on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ cd hub-controller-live

$ mvn spring-boot:run
----

== Interacting with the Application Locally

To interact with your booster while it's running locally, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/my_robot/ping


$ curl -X POST http://localhost:8080/api/my_robot/run

----


== Updating the Application
To update your application:

. Stop your application.
+
NOTE: To stop your running application in a Linux or macOS terminal, use `CTRL+C`. In a Windows command prompt, you can use `CTRL + Break(pause)`.

. Make your change (e.g. edit `src/main/resources/static/index.html`).
. Restart your application.
. Confirm your change appears.


== Running the Application on the OpenShift Cluster

To deploy your booster to a running OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u <username> -p <password>

$ oc project <teamname>-robot-app

$ mvn clean fabric8:deploy -Popenshift -DskipTests
----

== More Information
You can learn more about this booster and rest of the Spring Boot runtime in the link:http://launcher.fabric8.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].
